name: operator_srdit
params:
  in_channels: 1
  condition_channels: 1
  shape: [512, 512]
    
  # Sampler / schedule
  steps: 5
  sampler: 'AB2CN'        # 'Euler', 'AB2', 'AB2CN'
  L: 1.0                # domain half-length for coords / deriv
  
  # Training
  learning_rate: 1e-4