name: vlm
params:

    in_channels: 1
    condition_channels: 1
    shape: [512, 512]
    
    # AE architecture
    k: 8                    # pixel shuffle factor
    sdim: 2                 # spatial coord dims
    tdim: 16                # time embedding dims
    siren_width: null       # defaults to in_dim if None
    siren_layers: 5
    siren_w: 10.0
    encode_layers: 3
    
    # Sampler / schedule
    steps: 25
    sampler: 'AB2CN'        # 'Euler', 'AB2', 'AB2CN'
    L: 1.0                # domain half-length for coords / deriv

    seq_len: 50
    embed_dim: 8
    proj_dim: 96
    
    sem_dim: 64
    struct_dim: 64

    rules: True
    ae_type: mlp_deterministic

    pretrain_llm: /home/a1744874/ml/autoencoders/runs/mmai_apr26/1-llm/rpn_encoder/llm/PFSR6_/artifacts/checkpoints/last.ckpt
    use_llm: True

    # pretrain_vm: /home/a1744874/ml/autoencoders/runs/mmai_apr26/2-vlm/rpn_textvision/vlm/PGHOV_/artifacts/checkpoints/last.ckpt
    # pretrain_vm: /home/a1744874/ml/autoencoders/runs/mmai_apr26/2-vlm/rpn_textvision/vlm/PGOR0_/artifacts/checkpoints/last.ckpt
    pretrain_vm: /home/a1744874/ml/autoencoders/runs/mmai_apr26/2-vlm/rpn_textvision/vlm/PUXCH_/artifacts/checkpoints/last.ckpt


    # Training
    learning_rate: 1e-4