defaults:
  - model: tiny_hl
  - data: fashion_mnist
  - _self_

seed: 42

paths:
  data_root: ${oc.env:DATA_ROOT, ./data}
  artifacts_root: ${hydra:run.dir}/artifacts

run:
  name: ${hydra:job.name}
  tags: [autoencoder, baseline]

wandb:
  project: autoencoder-dev
  entity: null
  group: hydra
  mode: online
  name: ${run.name}
  tags: ${run.tags}

trainer:
  max_epochs: -1
  max_steps: 20000
  accelerator: auto
  devices: auto
  log_every_n_steps: 10
  precision: 32

git:
  sha: 000
  dirty: true
  changelog: NA

hydra:
  run:
    dir: runs/${data.name}/${model.name}/${sec_id:}
  job:
    config:
      override_dirname:
        kv_sep: '='
        item_sep: '_'
  sweep:
    dir: runs/sweep/${run.name}_${sec_id:}
    subdir: ${hydra.job.override_dirname}___${hydra.job.num}
